/**
 * Exchange Rate Management System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RateTrendPoint } from './rateTrendPoint';


export interface ExchangeRateTrendResponse { 
    fromCurrency: string;
    toCurrency: string;
    points: Array<RateTrendPoint>;
}

