/**
 * Exchange Rate Management System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RFC 9457 problem details
 */
export interface ProblemDetail { 
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
}

