/**
 * Exchange Rate Management System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RateTrendPoint { 
    rateDate: string;
    /**
     * Raw, unadjusted cross-rate, exact decimal (transported as string)
     */
    rate: string;
}

