/**
 * Exchange Rate Management System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshResult { 
    /**
     * Number of currencies successfully upserted in this run
     */
    currenciesCollected: number;
    /**
     * The rate date reported by the provider and persisted in this run
     */
    rateDate: string;
}

