/**
 * Exchange Rate Management System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceStatus { 
    status: ServiceStatus.StatusEnum;
    databaseConnected: boolean;
    timestamp: string;
}
export namespace ServiceStatus {
    export const StatusEnum = {
        Up: 'UP',
        Down: 'DOWN'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


