/**
 * Exchange Rate Management System API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrendInsightResponse { 
    fromCurrency: string;
    toCurrency: string;
    /**
     * The resolved (default-applied) start of the summarized range
     */
    startDate: string;
    /**
     * The resolved (default-applied) end of the summarized range
     */
    endDate: string;
    /**
     * Short plain-language narrative grounded strictly in the historical rate values for this range; never fabricated (see 503 response for the AI-unavailable case) 
     */
    narrative: string;
}

